version: '2'

services:
  db:
    build: ./db
    env_file: ./.dockerenv/db.env
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build: ./backend
    command: ./run_webapp.sh
    env_file: ./.dockerenv/backend.env
    expose:
      - "8000"
    links:
      - db
    volumes:
      - staticfiles:/static
    networks:
      - backend
      - frontend

  frontend:
    build: ./frontend
    env_file: ./.dockerenv/frontend.env
    links:
      - backend
    ports:
      - "80:80"
    volumes:
      - staticfiles:/var/www/static:ro
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  dbdata:
  staticfiles:
