version: '2'

services:
  db:
    build: ./db
    env_file: ./db/docker.env
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: gunicorn --config gunicorn_config.py home_web.wsgi
    environment:
      - DJANGO_CONFIGURATION=Prod
    env_file: ./backend/docker.env
    links:
      - db
    volumes:
      - staticfiles:/static

volumes:
  dbdata:
  staticfiles:
