version: '2'

services:
  db:
    build: ./db
    env_file: ./.dockerenv/db.env
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - django

  django:
    extends:
      file: common.yml
      service: backend
    command: ./run_webapp.sh
    expose:
      - "8000"
    links:
      - db
    volumes:
      - staticfiles:/static
    networks:
      - django
      - frontend

  frontend:
    build: ./frontend
    env_file: ./.dockerenv/frontend.env
    links:
      - django
    ports:
      - "80:80"
    volumes:
      - staticfiles:/var/www/static:ro
    networks:
      - frontend

networks:
  django:
  frontend:

volumes:
  dbdata:
  staticfiles:
